services:
  dashboard:
    build:
      context: ./icenet-dashboard
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
    depends_on:
      - tiler-api
    environment:
      - PYTHONPATH=/app/src
      - TITILER_URL=http://${HOST_IP}:${TILER_PORT}
      - DATA_URL=http://${HOST_IP}:${DATA_PORT}
      - DASHBOARD_PORT=${DASHBOARD_PORT}

  tiler-api:
    build:
      context: ./icenet-tiler-api
    ports:
      - "${TILER_PORT}:${TILER_PORT}"
      - "${DATA_PORT}:${DATA_PORT}"
    environment:
      - TILER_PORT=${TILER_PORT}
      - DATA_PORT=${DATA_PORT}
      - WORKERS=${WORKERS}
      - DATA_DIR=/app/mounted_vols/data
    volumes:
      - ./data:/app/mounted_vols/data
