#!/bin/bash
# Emit an extra Compose file that bind-mounts resolved symlink targets under
# ./data into the file-server (and optionally titiler) containers.
#
# Why: if ./data/ has symlinks, Docker cannot see the real host paths inside
# the nginx/file-server (or titiler) container unless those targets are
# mounted explicitly. Used by the Ansible deployment.
#
# Do NOT write compose.override.yaml: that file is reserved for local `make
# dev` dashboard source bind-mount (hot-reload). Ansible includes
# this file explicitly for every env.
#
# Usage:
#   ./generate_data_symlink_override.sh [output_file]
# Default output: compose.data-symlinks.yaml

set -euo pipefail

OUTPUT_FILE="${1:-compose.data-symlinks.yaml}"
DATA_DIR="./data"
CONTAINER_BASE="/usr/share/nginx/html/data"

VOLUME_ENTRIES=()

if [[ ! -d "$DATA_DIR" ]]; then
  rm -f "$OUTPUT_FILE"
  echo "No $DATA_DIR directory; removed $OUTPUT_FILE if present."
  exit 0
fi

while IFS= read -r link; do
  target=$(readlink -f "$link")
  name=$(basename "$link")

  if [[ -e "$target" ]]; then
    container_target="${CONTAINER_BASE}/${name}"
    VOLUME_ENTRIES+=("      - \"$target:$container_target:ro\"")
  else
    echo "Broken symlink: $link -> $target" >&2
  fi
done < <(find "$DATA_DIR" -maxdepth 1 -type l)

if ((${#VOLUME_ENTRIES[@]} > 0)); then
  {
    cat <<EOF
# Generated by generate_data_symlink_override.sh - do not edit by hand.
services:
  file-server:
    volumes:
EOF
    printf "%s\n" "${VOLUME_ENTRIES[@]}"
    # Titiler/read paths use /data; mirror resolved mounts there too.
    cat <<EOF
  titiler:
    volumes:
EOF
    for entry in "${VOLUME_ENTRIES[@]}"; do
      # Rewrite container path /usr/share/nginx/html/data -> /data
      echo "$entry" | sed 's|/usr/share/nginx/html/data|/data|'
    done
  } >"$OUTPUT_FILE"

  echo "Created $OUTPUT_FILE with ${#VOLUME_ENTRIES[@]} fixed symlink mounts."
else
  rm -f "$OUTPUT_FILE"
  echo "No top-level data symlinks; removed $OUTPUT_FILE if present."
fi
