- name: Install Python 3.12
  hosts: all
  become: true
  gather_facts: false

  vars:
    py312_path: /usr/bin/python3.12

  tasks:
    - name: Install Python 3.12 and pip
      ansible.builtin.dnf:
        name:
          - python3.12
          - python3.12-pip
          - python3.12-devel
        state: latest
